name: "Setup Node.js with Yarn"
description: "Sets up Node.js, enables Corepack, and installs Yarn dependencies"
author: "Chris Brewer"

inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "24"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    # Corepack (bundled with Node 16+) manages Yarn; enable it to use Yarn 4.x from packageManager in package.json
    - name: Enable Corepack
      run: corepack enable
      shell: bash
